# Generated by Django 5.2.7 on 2026-08-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrsession',
            name='qr_code_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
