# Generated by Django 5.2.7 on 2026-08-13 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_number', models.CharField(max_length=20)),
                ('receiver_number', models.CharField(max_length=20)),
                ('message_content', models.TextField()),
                ('msgID', models.CharField(max_length=255, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
