# Generated by Django 5.2.7 on 2026-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='messages_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveBigIntegerField(),
        ),
    ]
