# Generated by Django 5.2.7 on 2026-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_subscription_user_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
    ]
